def findall(string): ...
def findall_list(string, desc: bool = ...): ...
def replace(string, repl: str = ...): ...
def replace_with_desc(string, sep: str = ...): ...
def last_downloaded_timestamp(): ...
