env:
  browser: true
  es6: true
extends:
  - eslint:recommended
  - google
parserOptions:
  ecmaVersion: 8
  sourceType: script
rules:
  indent:
    - error
    - 4
  max-len:
    - error
    - code: 100
